version: 5.1.0
variant: default
logo: /img/logo.svg
head:
    favicon: /img/favicon.svg
    manifest:
        name:  Christopher Blog
        short_name: Chrisckey
        start_url: https://chrisvicky.github.io/
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        # About: /about
        About: /2022/11/12/aboutme
    links:
        GitHub:
            icon: fab fa-github
            url: https://github.com/chrisvicky
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        GitHub:
            icon: fab fa-github
            url: https://github.com/chrisvicky
article:
    highlight:
        theme: dracula
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: false
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
    index_pages: true
# comment:
#     type: disqus
#     shortname: ''
# donates:
#     -
#         type: afdian
#         url: ''
#     -
#         type: alipay
#         qrcode: ''
#     -
#         type: buymeacoffee
#         url: ''
#     -
#         type: patreon
#         url: ''
#     # -
#     #     type: paypal
#     #     business: ''
#     #     currency_code: USD
#     -
#         type: wechat
#         qrcode: ''
# share:
#     type: sharethis
#     install_url: ''
sidebar:
    left:
        sticky: true
    right:
        sticky: true
widgets:
    -
        position: left
        type: profile
        author: Christopher Liu
        author_title: College Student
        location: Chengdu, Sichuan, China
        avatar:  /myimg/yukinoshita_1.png
        avatar_rounded: true 
        gravatar: 
        follow_link: https://github.com/chrisvicky
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/chrisvicky
            Facebook:
                icon: fab fa-facebook
                url: https://facebook.com
            Twitter:
                icon: fab fa-twitter
                url: https://twitter.com
            Dribbble:
                icon: fab fa-dribbble
                url: https://dribbble.com
            RSS:
                icon: fas fa-rss
                url: /
    -
        position: left
        type: toc
        index: true
        # collapsed: true
        # depth: 3
    -
        position: right
        type: categories
    -
        position: right
        type: recent_posts
    -
        position: right
        type: tags
        order_by: name
        amount: 
        show_count: true
    -
        position: right 
        type: archives
          # -
          #     position: right
          #     type: links
          #     links:
          #         Hexo: https://hexo.io
          #         Bulma: https://bulma.io
    # -
    #     position: left
    #     type: subscribe_email
    #     description: 
    #     feedburner_id: ''
    # -
    #     position: left
    #     type: adsense
    #     client_id: ''
    #     slot_id: ''
    # -
    #     position: left
    #     type: followit
    #     description: 
    #     action_url: ''
    #     verification_code: ''
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
